#!/usr/bin/env node
import { Command } from "commander";
import { parseFlowFile } from "./parser.js";
import { FlowEngine } from "./engine.js";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";

const program = new Command();

program
  .name("codex-flow")
  .description("YAML-driven workflow engine powered by Codex")
  .version("0.1.0");

program
  .command("run")
  .description("Execute a flow file")
  .argument("<file>", "Path to YAML flow file")
  .option("-v, --var <key=value...>", "Override variables (key=value)")
  .option("--continue", "Continue on step failure", false)
  .option("--quiet", "Suppress step output", false)
  .action((file: string, options: { var?: string[]; continue: boolean; quiet: boolean }) => {
    const flowPath = resolve(file);
    const { flow } = parseFlowFile(flowPath);

    if (options.var) {
      for (const pair of options.var) {
        const [key, ...rest] = pair.split("=");
        if (key && rest.length > 0) {
          flow.variables = { ...(flow.variables ?? {}), [key]: rest.join("=") };
        }
      }
    }

    const logger = options.quiet
      ? () => {}
      : (msg: string) => process.stdout.write(msg + "\n");

    const engine = new FlowEngine({
      logger,
      stopOnError: !options.continue,
    });

    engine.run(flow).then((result) => {
      const exitCode = result.status === "success" ? 0 : 1;
      if (!options.quiet) {
        console.log(
          `\n${result.steps
            .map((s) => `  ${s.status === "success" ? "✓" : "✗"} ${s.stepName}`)
            .join("\n")}`
        );
      }
      process.exit(exitCode);
    });
  });

program
  .command("validate")
  .description("Validate a flow file without executing")
  .argument("<file>", "Path to YAML flow file")
  .action((file: string) => {
    try {
      const { flow, warnings } = parseFlowFile(resolve(file));
      console.log(`✅ Valid flow: ${flow.name} (${flow.steps.length} steps)`);
      if (warnings.length > 0) {
        console.log(`⚠️  Warnings:`);
        warnings.forEach((w) => console.log(`  - ${w}`));
      }
    } catch (err) {
      console.error(`❌ ${((err as Error).message)}`);
      process.exit(1);
    }
  });

program
  .command("init")
  .description("Generate a starter flow template")
  .argument("[name]", "Flow name", "my-flow")
  .action((name: string) => {
    const template = `# ${name} — generated by codex-flow init
name: ${name}
description: "A workflow to automate your development tasks"
variables:
  project_dir: "."

steps:
  - id: analyze
    name: "Analyze Project"
    type: codex
    prompt: "Analyze the project in {{project_dir}} and summarize its structure and key files."

  - id: plan
    name: "Create Plan"
    type: codex
    prompt: "Based on the analysis, create a step-by-step plan for the next improvement."

  - id: implement
    name: "Implement"
    type: codex
    prompt: "Implement the plan. Make minimal, focused changes."
`;
    const fileName = `${name.replace(/\s+/g, "-")}.flow.yaml`;
    console.log(`📄 Created: ${fileName}`);
    process.stdout.write(template);
  });

program.parse();
