#!/usr/bin/env node
import { Command } from "commander";
import { parseFlowFile, parseFlowYAML } from "./parser.js";
import { FlowEngine } from "./engine.js";
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { createInterface } from "node:readline";
import { executeCodexGenerate } from "./generator.js";
import { startStudio } from "./studio/server.js";
import { existsSync } from "node:fs";

const program = new Command();

program
  .name("codex-flow")
  .description("YAML-driven workflow engine powered by Codex")
  .version("0.1.0");

program
  .command("run")
  .description("Execute a flow file")
  .argument("<file>", "Path to YAML flow file")
  .option("-v, --var <key=value...>", "Override variables (key=value)")
  .option("--continue", "Continue on step failure", false)
  .option("--quiet", "Suppress step output", false)
  .action((file: string, options: { var?: string[]; continue: boolean; quiet: boolean }) => {
    const flowPath = resolve(file);
    const { flow } = parseFlowFile(flowPath);

    if (options.var) {
      for (const pair of options.var) {
        const [key, ...rest] = pair.split("=");
        if (key && rest.length > 0) {
          flow.variables = { ...(flow.variables ?? {}), [key]: rest.join("=") };
        }
      }
    }

    const logger = options.quiet
      ? () => {}
      : (msg: string) => process.stdout.write(msg + "\n");

    const engine = new FlowEngine({
      logger,
      stopOnError: !options.continue,
    });

    engine.run(flow).then((result) => {
      const exitCode = result.status === "success" ? 0 : 1;
      if (!options.quiet) {
        console.log(
          `\n${result.steps
            .map((s) => `  ${s.status === "success" ? "✓" : "✗"} ${s.stepName}`)
            .join("\n")}`
        );
      }
      process.exit(exitCode);
    });
  });

program
  .command("validate")
  .description("Validate a flow file without executing")
  .argument("<file>", "Path to YAML flow file")
  .action((file: string) => {
    try {
      const { flow, warnings } = parseFlowFile(resolve(file));
      console.log(`✅ Valid flow: ${flow.name} (${flow.steps.length} steps)`);
      if (warnings.length > 0) {
        console.log(`⚠️  Warnings:`);
        warnings.forEach((w) => console.log(`  - ${w}`));
      }
    } catch (err) {
      console.error(`❌ ${((err as Error).message)}`);
      process.exit(1);
    }
  });

program
  .command("init")
  .description("Generate a starter flow template")
  .argument("[name]", "Flow name", "my-flow")
  .option("-i, --interactive", "Launch interactive wizard")
  .action((name: string, options: { interactive: boolean }) => {
    if (options.interactive) {
      runInteractiveInit(name);
    } else {
      const template = generateBasicTemplate(name);
      const fileName = `${name.replace(/\s+/g, "-")}.flow.yaml`;
      writeFileSync(fileName, template);
      console.log(`📄 Created: ${fileName}`);
      console.log(`   Edit it, then run: codex-flow run ${fileName}`);
    }
  });

program
  .command("generate")
  .description("Generate a flow from a natural language description (powered by Codex)")
  .argument("<description>", "Describe what the flow should do")
  .option("-o, --output <file>", "Output file", "generated.flow.yaml")
  .option("--validate", "Validate the generated flow after creation", true)
  .action(async (description: string, options: { output: string; validate: boolean }) => {
    console.log(`\n🤖 Generating flow from: "${description}"\n`);
    const result = await executeCodexGenerate(description);

    if (result.error) {
      console.error(`❌ ${result.error}`);
      process.exit(1);
    }

    if (options.validate) {
      try {
        const { flow } = parseFlowYAML(result.yaml);
        console.log(`✅ Generated valid flow: ${flow.name} (${flow.steps.length} steps)`);
        console.log(`   Steps: ${flow.steps.map((s) => s.name).join(" → ")}`);
      } catch (err) {
        console.warn(`⚠️  Generated YAML may need manual fixes: ${(err as Error).message}`);
      }
    }

    writeFileSync(options.output, result.yaml);
    console.log(`\n📄 Saved to: ${options.output}`);
    console.log(`   Run it: codex-flow run ${options.output}`);
  });
function generateBasicTemplate(name: string): string {
  return `# ${name} — generated by codex-flow init
name: ${name}
description: "A workflow to automate your development tasks"
variables:
  project_dir: "."

steps:
  - id: analyze
    name: "Analyze Project"
    type: codex
    prompt: "Analyze the project in {{project_dir}} and summarize its structure and key files."

  - id: plan
    name: "Create Plan"
    type: codex
    prompt: "Based on the analysis, create a step-by-step plan for the next improvement."

  - id: implement
    name: "Implement"
    type: codex
    prompt: "Implement the plan. Make minimal, focused changes."
`;
}

async function runInteractiveInit(name: string) {
  const rl = createInterface({ input: process.stdin, output: process.stdout });

  const ask = (question: string): Promise<string> =>
    new Promise((resolveP) => rl.question(question, resolveP));

  console.log("\n🪄 codex-flow interactive wizard\n");
  console.log("Answer questions to generate a custom flow file.\n");

  const flowName = (await ask("Flow name [default: " + name + "]: ")).trim() || name;
  const description = (await ask("Description: ")).trim() || "Custom workflow";

  console.log("\n--- Variables (press Enter to skip) ---\n");
  const variables: Record<string, string> = {};
  while (true) {
    const varLine = (await ask("  key=value (or 'done' to finish): "));
    if (varLine.toLowerCase() === "done" || varLine === "") break;
    const [key, ...rest] = varLine.split("=");
    if (key && rest.length > 0) {
      variables[key.trim()] = rest.join("=").trim();
    }
  }

  console.log("\n--- Steps (press Enter on step name to finish) ---\n");
  const steps: Array<{ id: string; name: string; type: string; prompt?: string; command?: string; parallel?: boolean; timeout?: number }> = [];

  let stepNum = 1;
  while (true) {
    const stepName = (await ask(`  Step ${stepNum} name (Enter to finish): `)).trim();
    if (!stepName) break;

    const type = (await ask(`    Type [codex/shell/http/wait/condition] (default: codex): `)).trim() || "codex";

    let prompt: string | undefined;
    let command: string | undefined;

    if (type === "codex" || type === "condition") {
      prompt = await ask("    Prompt: ");
    } else if (type === "shell" || type === "http") {
      command = await ask("    Command/URL: ");
    } else if (type === "wait") {
      const ms = (await ask("    Wait ms (default: 1000): ")).trim() || "1000";
      command = ms;
    }

    const parallelInput = (await ask("    Parallel? [y/N] (default: N): ")).trim().toLowerCase();
    const parallel = parallelInput === "y" || parallelInput === "yes";

    const timeoutInput = (await ask("    Timeout ms (Enter to skip): ")).trim();
    const timeout = timeoutInput ? parseInt(timeoutInput, 10) : undefined;

    steps.push({
      id: stepName.toLowerCase().replace(/[^a-z0-9]/g, "-"),
      name: stepName,
      type,
      ...(prompt ? { prompt } : {}),
      ...(command ? { command } : {}),
      ...(parallel ? { parallel } : {}),
      ...(timeout ? { timeout } : {}),
    });

    stepNum++;
  }

  rl.close();

  const yaml = generateYAML(flowName, description, variables, steps);
  const fileName = `${flowName.replace(/\s+/g, "-")}.flow.yaml`;
  writeFileSync(fileName, yaml);

  console.log(`\n✅ Created: ${fileName}`);
  console.log(`   Validate: codex-flow validate ${fileName}`);
  console.log(`   Run: codex-flow run ${fileName}`);
}

function generateYAML(
  name: string,
  description: string,
  variables: Record<string, string>,
  steps: Array<{ id: string; name: string; type: string; prompt?: string; command?: string; parallel?: boolean; timeout?: number }>
): string {
  let yaml = `# ${name} — generated by codex-flow interactive wizard\n`;
  yaml += `name: ${name}\n`;
  yaml += `description: "${description}"\n`;

  if (Object.keys(variables).length > 0) {
    yaml += `variables:\n`;
    for (const [key, value] of Object.entries(variables)) {
      yaml += `  ${key}: "${value}"\n`;
    }
  }

  yaml += `\nsteps:\n`;
  for (const step of steps) {
    yaml += `  - id: ${step.id}\n`;
    yaml += `    name: "${step.name}"\n`;
    yaml += `    type: ${step.type}\n`;
    if (step.prompt) {
      yaml += `    prompt: ${escapeYamlString(step.prompt)}\n`;
    }
    if (step.command) {
      yaml += `    command: ${escapeYamlString(step.command)}\n`;
    }
    if (step.parallel) {
      yaml += `    parallel: true\n`;
    }
    if (step.timeout) {
      yaml += `    timeout: ${step.timeout}\n`;
    }
    yaml += `\n`;
  }

  return yaml;
}

function escapeYamlString(str: string): string {
  if (str.includes("\n") || str.includes("#") || str.includes(":")) {
    return `|\n      ${str.replace(/\n/g, "\n      ")}`;
  }
  return `"${str.replace(/"/g, '\\"')}"`;
}

program
  .command("studio")
  .description("Launch the visual flow editor in your browser")
  .option("-p, --port <number>", "Port number", "3210")
  .option("-f, --file <path>", "Load a flow file on startup")
  .action(async (options: { port: string; file?: string }) => {
    const port = parseInt(options.port, 10);
    const file = options.file ? resolve(options.file) : undefined;
    if (file && !existsSync(file)) {
      console.error(`❌ File not found: ${file}`);
      process.exit(1);
    }
    await startStudio({ port, initialFile: file });
  });

program.parse();
